esphome:
  name: cc1101
  
  libraries:
    - SPI
    
esp8266:
  board: d1_mini
  framework:
    version: latest

    
external_components:
  - source:
      type: git
      url: https://github.com/JNSwanson/ESP-Home-iBoost/
      #type: local # Alternative.  Clone from git and point to the local files:
      #path: "C:\\Users\\<your Name>\\iboostSrc\\ESP-Home-iBoost\\esphome\\components" 
    components:
      - cc1101    
      - iboost
 
cc1101:
text_sensor: 

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
 - platform: esphome
   password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Cc1101 Fallback Hotspot"
    password: "????????"
 
  # Optional MQTT support 
#mqtt:
#  topic_prefix: "iBoost"
#  discovery: false
#  broker: !secret mqtt_broker_ipaddress
#  port: 1883
#  username: !secret mqtt_user
#  password: !secret mqtt_password
#  discovery_prefix: homeassistant
  
# Optional Web configuration entry
web_server:
  port: 80
  version: 1

captive_portal:

    
sensor:
  - platform: iboost
    id: iboost_iboost_id
    
    heating_import:
      name: "iBoost Import"
      unit_of_measurement: "W"
      accuracy_decimals: 0
      icon: "mdi:solar-power"

    heating_power:
      name: "iBoost Power"
      unit_of_measurement: "W"
      accuracy_decimals: 0
      icon: "mdi:solar-power"
      device_class: power

    heating_today:
      name: "iBoost Today"
      unit_of_measurement: "Wh"
      accuracy_decimals: 0
      device_class: energy
      icon: "mdi:solar-power"
      state_class: total_increasing

    heating_yesterday:
      name: "iBoost Yesterday"
      unit_of_measurement: "Wh"
      accuracy_decimals: 0
      icon: "mdi:solar-power"
      device_class: energy
      state_class: total_increasing

    heating_last_7:
      name: "iBoost Last 7 Days"
      unit_of_measurement: "Wh"
      accuracy_decimals: 0
      icon: "mdi:solar-power"
      state_class: total_increasing
      device_class: energy

    heating_last_28:
      name: "iBoost Last 28 Days"
      unit_of_measurement: "Wh"
      accuracy_decimals: 0
      icon: "mdi:solar-power"
      device_class: energy
      state_class: total_increasing

    heating_last_gt:
      name: "iBoost Total"
      unit_of_measurement: "Wh"
      accuracy_decimals: 0
      icon: "mdi:solar-power"
      device_class: energy
      state_class: total_increasing

    heating_boost_time:
      name: "iBoost Boost Time Remaining"
      unit_of_measurement: "Min"
      accuracy_decimals: 0
      device_class: duration
      icon: "mdi:solar-power"

# Ensure `text_sensor:` is at the correct level
#text_sensor:
#  - platform: cc1101
#  
#  - platform: iboost
    heating_mode:
      name: "iBoost Mode"
      icon: "mdi:solar-power"

    heating_warn:
      name: "iBoost Warn"
      icon: "mdi:solar-power"




button:
  - platform: template
    name: "iBoost Manual Boost START"
    id: BoostStart
    icon: "mdi:solar-power"
    on_press:
      then:
        - lambda: |-
            id(iboost_iboost_id)->boost(id(boostTime).state);

  - platform: template
    name: "iBoost Manual Boost CANCEL"
    id: BoostCancel
    icon: "mdi:solar-power"
    on_press:
      then:
        - lambda: |-
            id(iboost_iboost_id)->boost(0);
            
number:
  - platform : template
    name: "iBoost Manual Boost Time"
    id: boostTime
    icon: "mdi:solar-power"
    unit_of_measurement: "Minutes" 
    optimistic: true
    initial_value: 15
    min_value: 0
    max_value: 120
    step: 15  
